version: '3.1'

services:

  master:
    image: pgkit:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    hostname: master
    restart: always
    command: 'bash -c "/init.sh && sleep 3600"'
    volumes:
      - ./init.sh:/init.sh:ro
    networks:
      - postgres

  replica:
    image: pgkit:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS: ${OS}
        OS_VERSION: ${OS_VERSION}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    hostname: replica
    restart: always
    command: 'bash -c "/init.sh && exec /lib/systemd/systemd" && sleep 3600'
    privileged: true
    volumes:
      - ./init.sh:/init.sh:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
