name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'dist/**'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/python-publish.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "deployment/docker-compose.yml" up -d --build
      
      - name: Run tests
        uses: runforesight/workflow-telemetry-action@v1.8.0
        run: docker-compose -f "deployment/docker-compose.yml" exec -T replica python3 integration-test.py
