name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'dist/**'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/python-publish.yml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        os_version: [20.04, 22.04]
        postgres_version: [9.5, 10, 11, 12, 13, 14, 15]

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1

      - name: Start containers
        run: docker-compose -f "deployment/docker-compose.yml" up -d --build
        env:
          OS: ${{matrix.os}}
          OS_VERSION: ${{matrix.os_version}}
          POSTGRES_VERSION: ${{matrix.postgres_version}}
      
      - name: Sleep so containers are ready
        run: sleep 15
      
      - name: Check container status
        run : docker ps -a
      
      - name: Run tests
        run: docker-compose -f "deployment/docker-compose.yml" exec -T replica python3 integration-test.py
