name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'dist/**'
      - 'LICENSE'
      - '.gitignore'
      - '.github/workflows/python-publish.yml'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1

      - name: Start containers
        run: docker-compose -f "deployment/docker-compose.yml" up -d --build
      
      - name: Sleep so containers are ready
        run: sleep 30
      
      - name: Check container status
        run : docker ps -a
      
      - name: Container logs
        run: docker logs deployment_replica_1
      
      - name: Run tests
        run: docker-compose -f "deployment/docker-compose.yml" exec -T replica python3 integration-test.py
