name: Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "deployment/docker-compose.yml" up -d --build
      
      - name: Run tests
        run: docker-compose exec replica python3 deployment/integration-test.py
